version: '3.7'

services:
  docker_registry_proxy:
    image: runalsh/docker-registry-proxy:latest # Check and make sure this is the last released version
    env_file: # This contains REGISTRIES and AUTH_REGISTRIES
      - ./secrets.env
    environment:
      - CACHE_MAX_SIZE=1g
      - ENABLE_MANIFEST_CACHE=true
      - ALLOW_PUSH=true
    volumes:
      # Format: <host-path>:<container-path>; adapt to your needs
      - ./docker-registry-proxy_cache:/docker_mirror_cache # This will be up to CACHE_MAX_SIZE big
      - ./docker-registry-proxy_certs:/ca
      - ./auth:/etc/angie/auth
    ports:
      - 0.0.0.0:5003:3128 # 0.0.0.0 binds to all interfaces
